### ISSUE TITLE
Add "Human/Any" to "Best Day" options

### ISSUE THREAD

**Issue by alexlande** [cascadiajs/opencfp#4]
Some folks have been confused and thought that we were only accepting talks that were strictly about CSS/JS/Node due to the "Best Day" field.

It would be nice to add "Any" and/or "Human" as options to encourage. The field should probably have a different name since there is no "Human" day and that's potentially confusing. Some options:
- Best Day: CSS/Browser/Node/Human/Any
- Best Day: CSS/Browser/Node/Any
- Topic: CSS/Browser/Node/Human
- Type: CSS/Browser/Node/Human/Any

/cc @davethegr8

**Comment by RuthieB** [comment]
I am in favor of adding the "Any" option for "Best Day" or "Topic." It will be less confusing for submitters than "Human," and encompasses literally ALL talks that don't obviously fit in one of the three days.
